// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx49EKCoUCxVec9h9AbTWF8BKC35VWspE',
    appId: '1:897281740576:web:7116ac216d8b89b18f1145',
    messagingSenderId: '897281740576',
    projectId: 'skillrise-7852c',
    authDomain: 'skillrise-7852c.firebaseapp.com',
    storageBucket: 'skillrise-7852c.firebasestorage.app',
    measurementId: 'G-THLJYGMCN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdGSBQURTgmtz4CEwlhLKyY50VGwU8iz0',
    appId: '1:897281740576:android:6d75bd1668bc0f0f8f1145',
    messagingSenderId: '897281740576',
    projectId: 'skillrise-7852c',
    storageBucket: 'skillrise-7852c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx49EKCoUCxVec9h9AbTWF8BKC35VWspE',
    appId: '1:897281740576:web:d5107a04744466e58f1145',
    messagingSenderId: '897281740576',
    projectId: 'skillrise-7852c',
    authDomain: 'skillrise-7852c.firebaseapp.com',
    storageBucket: 'skillrise-7852c.firebasestorage.app',
    measurementId: 'G-65EP9F2NWF',
  );
}
